add support email to readme
Open-Telecoms-Data/open-fibre-data-standard pull request #201
Opened 2022-11-25 12:51 UTC by lgs85

**Related issues**

**Description**

**Merge checklist**

- [ ] Update the changelog ([style guide](https://ofds-standard-development-handbook.readthedocs.io/en/latest/style/changelog_style_guide.html))
- [ ] Run `./manage.py pre-commit` to update derivative schema files, reference documentation and examples

If there are changes to `network-schema.json`, `network-package-schema.json`, `reference/publication_formats/json.md`, `reference/publication_formats/geojson.md` or `guidance/publication.md#how-to-publish-large-networks`, update the relevant manually authored examples:

- [ ] `examples/json/`:
  - [ ] `network-package.json`
  - [ ] `api-response.json`
  - [ ] `multiple-networks.json`
  - [ ] `network-embedded.json`
  - [ ] `network-separate-endpoints.json`
  - [ ] `network-separate-files.json`
  - [ ] `nodes-endpoint.json`
  - [ ] `spans-endpoint.json`
- [ ] `examples/geojson/`:
  - [ ] `api-response.geojson`
  - [ ] `multiple-networks.geojson`

If you used a validation keyword, type or format that is not [already used in the schema](https://ofds-standard-development-handbook.readthedocs.io/en/latest/standard/schema.html#json-schema-usage):

- [ ] Update the list of validation keywords, types or formats in [JSON Schema usage](https://ofds-standard-development-handbook.readthedocs.io/en/latest/standard/schema.html#json-schema-usage).
- [ ] Add a field that fails validation against the new keyword, type or format to [`network-package-invalid.json`](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/0.1-dev/examples/json/network-package-invalid.json).
- [ ] Check that [OFDS CoVE](https://ofds.cove.opendataservices.coop/) reports an appropriate validation error.

If you added a normative rule that is not encoded in JSON Schema:

- [ ] Update the list of [other normative rules](https://ofds-standard-development-handbook.readthedocs.io/en/latest/standard/schema.html#other-normative-rules).
- [ ] Add a field that does not conform to the rule to [`network-package-additional-checks.json`](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/0.1-dev/examples/json/network-package-additional-checks.json).
- [ ] Open a [new issue](https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/new/choose) to add an additional check to Lib Cove OFDS.

If there are changes to `examples/geojson/nodes.geojson` or `examples/geojson/spans.geojson`, check and update the data use examples:

- [ ] `examples/leaflet/leaflet.ipynb`
- [ ] `examples/qgis/geojson.qgs`

2022-11-28 20:55 UTC, duncandewhurst commented
Should we also add a support page to the standard documentation? For reference, OCDS has a [Getting Help](https://standard.open-contracting.org/latest/en/support/) page.

2022-12-01 15:35 UTC, lgs85 commented
@duncandewhurst good plan - have now added a (heavily cribbed) support page.

2022-12-01 22:12 UTC, duncandewhurst requested changes, later dismissed
Looks good! Just a few minor copy-edits.

2022-12-01 22:12 UTC, duncandewhurst commented on docs/support/index.md
> +This page describes how you can get help with publishing or using OFDS data.
Expand first use of 'OFDS':

```suggestion
This page describes how you can get help with publishing or using Open Fibre Data Standard (OFDS) data.
```

2022-12-01 22:12 UTC, duncandewhurst commented on docs/support/index.md
> +## OFDS Helpdesk
I prefer to avoid 'helpdesk' terminology as many people read it to mean resetting passwords etc. :-)

```suggestion
## OFDS Support Team
```

2022-12-01 22:12 UTC, duncandewhurst commented on docs/support/index.md
> +The Open Fibre Data Standard (OFDS) Helpdesk is available to support you in publishing or using OFDS data, and to assist in the ongoing development of the standard.
See previous comments.

```suggestion
The OFDS Support Team is available to support you in publishing or using OFDS data and to assist in the ongoing development of the standard.
```

2022-12-01 22:12 UTC, duncandewhurst commented on docs/support/index.md
> +If you are planning to publish or use OFDS data, then the OFDS Helpdesk is on-hand to offer advice and input, by:
```suggestion
If you are planning to publish or use OFDS data, then the OFDS Support Team is on-hand to offer advice and input, by:
```

2022-12-01 22:12 UTC, duncandewhurst commented on docs/support/index.md
> +Helpdesk support is delivered through collaboration with [Open Data Services](https://opendataservices.coop).
```suggestion
Support is delivered in collaboration with [Open Data Services Co-operative](https://opendataservices.coop).
```

2022-12-01 22:12 UTC, duncandewhurst commented on docs/support/index.md
> +Please e-mail [openfibre@opendataservices.coop](mailto:openfibre@opendataservices.coop) with your questions, and a member of the OFDS Helpdesk will be in touch with you soon.
```suggestion
Please e-mail [openfibre@opendataservices.coop](mailto:openfibre@opendataservices.coop) with your questions, and a member of the OFDS Support Team will be in touch with you soon.
```

2022-12-01 22:12 UTC, duncandewhurst commented on docs/support/index.md
> +You can also contribute directly to public discussions about implementing the standard and give feedback on its development, via the [discussion tracker](https://github.com/Open-Telecoms-Data/open-fi
```suggestion
You can contribute directly to public discussions about implementing the standard and give feedback on its development via the [discussion tracker](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/discussions). You can also [raise an issue](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues) to make a technical contribution.
```

2022-12-02 09:06 UTC, odscjames approved these changes

2022-12-02 09:08 UTC, merged