Add .networkProviders to Span and Node, remove .networkProvider
Open-Telecoms-Data/open-fibre-data-standard pull request #234
Opened 2022-12-15 23:45 UTC by duncandewhurst

**Related issues**

* Closes #210

**Description**

**Merge checklist**

- [x] Update the changelog ([style guide](https://ofds-standard-development-handbook.readthedocs.io/en/latest/style/changelog_style_guide.html))
- [x] Run `./manage.py pre-commit` to update derivative schema files, reference documentation and examples

If there are changes to `network-schema.json`, `network-package-schema.json`, `reference/publication_formats/json.md`, `reference/publication_formats/geojson.md` or `guidance/publication.md#how-to-publish-large-networks`, update the relevant manually authored examples:

- [x] `examples/json/`:
  - [x] `network-package.json`
  - [x] `api-response.json`
  - [x] `multiple-networks.json`
  - [x] `network-embedded.json`
  - [x] `network-separate-endpoints.json`
  - [x] `network-separate-files.json`
  - [x] `nodes-endpoint.json`
  - [x] `spans-endpoint.json`
- [x] `examples/geojson/`:
  - [ ] `api-response.geojson`
  - [ ] `multiple-networks.geojson`

If you used a validation keyword, type or format that is not [already used in the schema](https://ofds-standard-development-handbook.readthedocs.io/en/latest/standard/schema.html#json-schema-usage):

- [ ] Update the list of validation keywords, types or formats in [JSON Schema usage](https://ofds-standard-development-handbook.readthedocs.io/en/latest/standard/schema.html#json-schema-usage).
- [ ] Add a field that fails validation against the new keyword, type or format to [`network-package-invalid.json`](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/0.1-dev/examples/json/network-package-invalid.json).
- [ ] Check that [OFDS CoVE](https://ofds.cove.opendataservices.coop/) reports an appropriate validation error.

If you added a normative rule that is not encoded in JSON Schema:

- [ ] Update the list of [other normative rules](https://ofds-standard-development-handbook.readthedocs.io/en/latest/standard/schema.html#other-normative-rules).
- [ ] Add a field that does not conform to the rule to [`network-package-additional-checks.json`](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/0.1-dev/examples/json/network-package-additional-checks.json).
- [ ] Open a [new issue](https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/new/choose) to add an additional check to Lib Cove OFDS.

If there are changes to `examples/geojson/nodes.geojson` or `examples/geojson/spans.geojson`, check and update the data use examples:

- [x] `examples/leaflet/leaflet.ipynb`
- [x] `examples/qgis/geojson.qgs`

2022-12-16 16:57 UTC, lgs85 approved these changes
Thanks Duncan, this is all looking great and I think you've covered everything. 

I'm not entirely happy with the way that we deal with fields like `capacity`, but think that this is the result of trying to do two things with one schema (i.e. represent both dispersed and centralised publishing models). I think that this works for now, and we can think about longer term options separately.

2022-12-16 17:16 UTC, lgs85 requested changes
Looking at this again, we need to resolve the conflict issues with `network-schema.csv` in particular, which has undergone substantial changes in a parallel PR. I can pick this up early next week if you don't get the chance @duncandewhurst

2022-12-20 02:31 UTC, duncandewhurst commented
I've merged `0.1-dev` into this branch, run `./manage.py pre-commit` and resolved the merge conflicts.

2022-12-20 10:35 UTC, lgs85 approved these changes

2022-12-20 10:36 UTC, merged