codelists: reorder codelists
Open-Telecoms-Data/open-fibre-data-standard pull request #280
Opened 2024-04-16 09:53 UTC by odscjen

**Related issues**

closes #209 

**Description**

**Merge checklist**

- [ ] Update the changelog ([style guide](https://ofds-standard-development-handbook.readthedocs.io/en/latest/style/changelog_style_guide.html))
- [ ] Run `./manage.py pre-commit` to update derivative schema files, reference documentation and examples

If there are changes to `network-schema.json`, `network-package-schema.json`, `reference/publication_formats/json.md`, `reference/publication_formats/geojson.md` or `guidance/publication.md#how-to-publish-large-networks`, update the relevant manually authored examples:

- [ ] `examples/json/`:
  - [ ] `network-package.json`
  - [ ] `api-response.json`
  - [ ] `multiple-networks.json`
  - [ ] `network-embedded.json`
  - [ ] `network-separate-endpoints.json`
  - [ ] `network-separate-files.json`
  - [ ] `nodes-endpoint.json`
  - [ ] `spans-endpoint.json`
- [ ] `examples/geojson/`:
  - [ ] `api-response.geojson`
  - [ ] `multiple-networks.geojson`

If you used a validation keyword, type or format that is not [already used in the schema](https://ofds-standard-development-handbook.readthedocs.io/en/latest/standard/schema.html#json-schema-usage):

- [ ] Update the list of validation keywords, types or formats in [JSON Schema usage](https://ofds-standard-development-handbook.readthedocs.io/en/latest/standard/schema.html#json-schema-usage).
- [ ] Add a field that fails validation against the new keyword, type or format to [`network-package-invalid.json`](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/0.1-dev/examples/json/network-package-invalid.json).
- [ ] Check that [OFDS CoVE](https://ofds.cove.opendataservices.coop/) reports an appropriate validation error.

If you added a normative rule that is not encoded in JSON Schema:

- [ ] Update the list of [other normative rules](https://ofds-standard-development-handbook.readthedocs.io/en/latest/standard/schema.html#other-normative-rules).
- [ ] Add a field that does not conform to the rule to [`network-package-additional-checks.json`](https://github.com/Open-Telecoms-Data/open-fibre-data-standard/blob/0.1-dev/examples/json/network-package-additional-checks.json).
- [ ] Open a [new issue](https://github.com/Open-Telecoms-Data/lib-cove-ofds/issues/new/choose) to add an additional check to Lib Cove OFDS.

If there are changes to `examples/geojson/nodes.geojson` or `examples/geojson/spans.geojson`, check and update the data use examples:

- [ ] `examples/leaflet/leaflet.ipynb`
- [ ] `examples/qgis/geojson.qgs`

2024-04-16 11:23 UTC, odscjen commented
reporting broken link

> (guidance/publication: line  348) broken    https://linux.die.net/man/3/libuuid - 403 Client Error: Forbidden for url: https://linux.die.net/man/3/libuuid

but its not broken, following that url takes you to a working webpage, all be it one with an irritating popup

2024-04-16 11:24 UTC, odscjen commented
It's also unclear why running `manage/py pre-commit` changed 2 example files?

2024-05-28 16:33 UTC, odscjen commented
have created an issue about the pre-commit problem https://github.com/Open-Telecoms-Data/open-fibre-data-standard/issues/285

2024-05-28 16:37 UTC, odscjen commented
https://github.com/Open-Telecoms-Data/open-fibre-data-standard/pull/284 to fix linkcheck error, once that's merged into main, rebase this branch/merge main into this branch

2024-06-11 13:57 UTC, duncandewhurst requested changes
Fine to merge once my comment is resolved.

2024-06-11 13:57 UTC, duncandewhurst commented on codelists/closed/spanStatus.csv
>  proposed,Proposed,Planning for the span is at an early stage and financing for its construction is not yet finalised.
'proposed' should come before 'planned' as in `nodeStatus.csv`

2024-06-18 14:32 UTC, odscjen commented
thanks @duncandewhurst but can't merge until you officially approve :)

2024-06-19 09:23 UTC, duncandewhurst approved these changes

2024-06-19 09:28 UTC, merged